function getCharacterAge(player: player, character: string) :: number:
  set {_value} to yaml value "character.%{_character}%.age" from "player-%{_player}'s uuid%"
  set {_number} to "%{_value}%" parsed as number

  return {_number}

function setCharacterAge(player: player, character: string, age: number):
  set yaml value "character.%{_character}%.age" from "player-%{_player}'s uuid%" to {_age}
  save yaml "player-%{_player}'s uuid%"