# Функция, которая возвращает булевое значение
# Обозначает, можно ли взять комнату в оренду
function FlatsModule_isRentable(modifiers: strings) :: boolean:
  {_modifiers::*} contains "rentable":
    return true
  else:
    return false

# Функция, которая возвращает булевое значение
# Описывает, можно ли купить комнату на постоянной основе
function FlatsModule_isBuyable(modifiers: strings) :: boolean:
  {_modifiers::*} contains "buyable":
    return true
  else:
    return false