function WorkModule_LoadHeaverHolograms(player: player):
  set {_locations::*} to WorkModule_GetHeaverHologramLocations()
  
  loop {_locations::*}:
    # Берём данные
    set {_location} to location of block at loop-value

    set {workers::%{_player}%::viewWorker::block::%{_location}%::type} to "hologram"
    set {workers::%{_player}%::viewWorker::block::%{_location}%::hoverAction} to "WP_Holo_HeaverCreate"
    set {workers::%{_player}%::viewWorker::block::%{_location}%::clickAction} to "WP_Holo_HeaverClick"