function getRoomInformationItem(roomId: string) :: item:
  set {_information} to player head named "&e &fИнформация о квартире" with lore ""
  add "{SkullOwner:{Id:""08a21c84-663b-4638-a31e-2f0423a3853f"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzY2OTJmOTljYzZkNzgyNDIzMDQxMTA1NTM1ODk0ODQyOThiMmU0YTAyMzNiNzY3NTNmODg4ZTIwN2VmNSJ9fX0=""}]}}}" to item-nbt of {_information}

  return {_information}