command help:
  trigger:
    open virtual chest inventory with size 5 named "&8Помощь" to player

    # Пустые слоты
    set {_empty} to player head named "&f"
    add "{SkullOwner:{Id:""ee6cb849-1384-4efa-bed7-23ff26bf79b1"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWQ5MzExN2I5ZTE4MGUwZGMzOWU1ZThhMDUwODQ4MmNmMWY2MGU0NDZlMDIyOTc4ZmUwNjUxYTU2MmE1OTdmIn19fQ==""}]}}}" to {_empty}'s nbt

    set {_slots::*} to 3,4,5, 20,21,22,23,24, 29,30,31,32,33
    format gui slot {_slots::*} of player with {_empty}
